### ISSUE TITLE
[Question]: Are there docs available?

### ISSUE THREAD

**Issue by LukeTowers** [Blobfolio/blob-common#1]
Hello,

I'm interested in potentially using this package to do SVG sanitizing in OctoberCMS, however I don't see any docs for how to go about doing that. I read https://blobfolio.com/2017/03/when-a-stranger-calls-sanitizing-svgs/ and it seems like this library would fit our needs perfectly but I need documentation in order to figure out how to use the library.

**Comment by joshstoik1** [comment]
Hi @LukeTowers,

For usage details, you could take a look at the Wiki, starting [here](https://github.com/Blobfolio/blob-common/wiki/Sanitizing-and-Validation#svg).

But if you're just looking to get some degree of SVG sanitizing into the OctoberCMS core, you probably don't want to add the entire `blob-common` library to your dependency chain — 99% of the code has nothing to do with SVGs, and some of the unrelated datasets are fairly large. Haha.

Instead, I'd recommend jumping into the [source](https://github.com/Blobfolio/blob-common/blob/master/lib/blobfolio/common/ref/sanitize.php#L1105) to get a sense of the tasks it is performing so that you can rewrite/port the few relevant methods directly to your project. Also, there are some nice example SVGs for unit testing, etc., [here](https://github.com/Blobfolio/blob-common/tree/master/tests/assets).

If you run into any issues or come up with any specific questions, please don't hesitate to reach out. I'm happy to help!
